name: Coverity Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * 0'  # Runs every Sunday at 2 AM UTC

jobs:
  coverity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permissions for Gradle wrapper
        run: chmod +x gradlew

      - name: Build project (Check if it compiles before Coverity scan)
        run: ./gradlew assembleDebug --stacktrace

      - name: Download Coverity Analysis Tool
        run: |
          wget --post-data "token=${{ secrets.COVERITY_TOKEN }}&project=${{ github.repository }}" -O coverity_tool.tgz https://scan.coverity.com/download/linux64
          tar -xvzf coverity_tool.tgz

      - name: Run Coverity Build
        run: |
          ./cov-analysis*/bin/cov-build --dir cov-int ./gradlew assembleDebug

      - name: Compress analysis results
        run: tar czvf cov-int.tgz cov-int

      - name: Upload results to Coverity
        run: |
          curl --form token=${{ secrets.COVERITY_TOKEN }} \
               --form email="your-email@example.com" \
               --form file=@cov-int.tgz \
               --form version="JetpackCompose" \
               --form description="Jetpack Compose Project Scan" \
               https://scan.coverity.com/builds?project=${{ github.repository }}
